package com.codeglo.sampleapp.database.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.parcelize.Parcelize

@Parcelize
@Entity(tableName = "image_table") // User Entity represents a table within the database.
data class Image(
    @PrimaryKey(autoGenerate = true)
    val id: Int, // <- 'id' is the primary key which will be autogenerated by the Room library.
    val url: String,
    val isChecked: Boolean,
): Parcelable